#! /bin/bash

select v in power safe; do

    case $v in
     power)
         for file in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor; do echo "performance" > $file; done
         echo $(cat /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor)
         exit;;
     
     safe) for file in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor; do echo "powersave" > $file; done
         echo $(cat /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor)
         exit;;
    esac
done


